name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ 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 }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
